### PR TITLE
style: Add DaisyUI card to all jokes 🚀

### LINKED ISSUE #1: Align joke history to center of the screen
Ideally this component would be centered on the screen as of the timeline vertical line.
Most ideally, this component should be re-made to a better looking one. Either a list of cards of a better looking timeline

### PR DESCRIPTION
**Pull request by rondDev**
Added daisyui dependency and added cards for both today's joke and joke

Fixes #1

### CODE REVIEW

**Comment by danicunhac** [comment]
Thank you for your contribution @rondDev! It's looking good!

I'd like to suggest a few changes:

1. The cards are bit too big, I think we could make them just a bit smaller to keep the simple layout.
2. Would look better if the previous joke cards are aligned to the left, close to the timeline.
3. I'd like to keep the past jokes without the `- Dad` part. The joke of the day can keep it

**Review by danicunhac — CHANGES_REQUESTED** [review]
Thank you for your contribution @rondDev! It's looking good!

I'd like to suggest a few changes:

1. The cards are bit too big, I think we could make them just a bit smaller to keep the simple layout.
2. Would look better if the previous joke cards are aligned to the left, close to the timeline.
3. I'd like to keep the past jokes without the `- Dad` part. The joke of the day can keep it

**Comment by rondDev** [comment]
Hey, I advise you or someone else take my PR and modify it, I can't seem to get supabase to work, so I would have to use local variables and such....

**Comment by danicunhac** [comment]
> Hey, I advise you or someone else take my PR and modify it, I can't seem to get supabase to work, so I would have to use local variables and such....

You can create you own Supabase database, and create the `jokes` table with the script below.
I'll add docs on how to setup the environment variables, but it shouldn't be hard. You'll just need `SUPABASE_URL`, `SUPABASE_KEY` and an optional `OPENAI_API_KEY` if you intend to test generating new jokes.
```sql
create table
  public.jokes (
    id bigint generated by default as identity not null,
    created_at date not null,
    joke text not null,
    constraint jokes_pkey primary key (created_at)
  ) tablespace pg_default;
  ```

**Pull request closed without merging**
